name: PR Title

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, synchronize]

env:
  CONVCO_VERSION: v0.4.2

jobs:
  validate:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - name: Install convco
        run: |
          curl -sSfL "https://github.com/convco/convco/releases/download/${{ env.CONVCO_VERSION }}/convco-ubuntu.zip" \
            | zcat \
            > /usr/local/bin/convco
          chmod +x /usr/local/bin/convco
      - name: Check PR Title is Conventional
        run: |
          echo "${{ github.event.pull_request.title }}" \
            | convco check \
              --from-stdin \
              --config .github/versionrc
